[package]
name = "rust-server"
description = "A simple rust opcua server"
homepage = "https://github.com/hen3u/opcua-server"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "^0.4", features = ["serde"] }
log = "^0.4"
log4rs = "1.2"
tokio = { version = "^1", features = ["full"] }

[dependencies.opcua]
git = "https://github.com/FreeOpcUa/rust-opcua.git"
branch = "master"
#rev = "..."
features = ["server", "console-logging"]
default-features = false